spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
