spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmall?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
server:
  port: 8500
mybatis:
  mapper-locations: classpath*:cn/exrick/user/mapper/*.xml
  type-aliases-package: cn.exrick.user.entity
logging:
  level:
    "org.mybatis": debug
    "com.wy.model": debug
    "org.springframework.transaction": debug
    "org.springframework.web": debug
